import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "next/head";
import { UserContextProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Migrating from the pages directory:
// The RootLayout replaces the _app.js and _document.js files.

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserContextProvider>
          <Header />
          <div className="flex flex-col min-h-screen relative bg-red-500">
            {children}
          </div>
          <Footer />
        </UserContextProvider>
      </body>
    </html>
  );
}
